on: 
  push:
    branches:
      - "main"
jobs:
  gh-pages-deployment:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Deploy application
        run: |
          npm install
          npm run deploy
    
